language: node_js

node_js:
    - "0.12"

before_install:
    - pushd "${HOME}"
    - curl -L "https://cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz" | gunzip -c | tar x
    - cd cmake-*/bin && export PATH="${PWD}:${PATH}"
    - popd
    - cmake --version
    - env

script:
    - npm install
    - ./node_modules/.bin/grunt
    - rm -f /tmp/vgl-serve.txt
    - ./node_modules/.bin/grunt serve-test >/tmp/vgl-serve.txt 2>&1 &
    - until grep -s 'Web server started on port' /tmp/vgl-serve.txt; do sleep 1; done
    - mkdir _build
    - cd _build
    - cmake ..
    - make
    - ctest -j 3 -VV -S ../cmake/travis_build.cmake || true
    - if [ -f test_failed ] ; then false ; fi

sudo: False
